CREATE OR ALTER PROCEDURE [dbo].[PRO_THEM_TAIKHOAN]
    @P_TENDANGNHAP VARCHAR(100),
    @P_MATKHAU VARCHAR(255),
    @P_HOTEN NVARCHAR(100),
    @P_GIOITINH NVARCHAR(10),
    @P_NGAYSINH DATE,
    @P_SDT VARCHAR(15),
    @P_CCCD VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @V_TAIKHOAN_ID UNIQUEIDENTIFIER = NEWID();

    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Thêm tài khoản
        INSERT INTO [dbo].[TAIKHOAN] (ID, TENDANGNHAP, MATKHAU, VAITRO)
        VALUES (@V_TAIKHOAN_ID, @P_TENDANGNHAP, @P_MATKHAU, 'quantri');


        COMMIT TRANSACTION;
        SELECT 200 AS StatusCode, N'Thêm giảng viên thành công!' AS Message;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 500 AS StatusCode, ERROR_MESSAGE() AS Message;
    END CATCH
END
GO